### ISSUE TITLE
dplyr

### ISSUE THREAD

**Issue by paocorrales** [yabellini/fromSpreadSheetToR#6]
Para los graficos del ejemplo necesitamos tambien filter().

Y tal vez se puede incluir algun ejemplo con mutate(), creo que no lleva muchisimo mas tiempo!

**Comment by yabellini** [comment]
Si de acuerdo! No llegué a terminarlo.

**Comment by paocorrales** [comment]
Avanso con la ultima parte pero no prometo nada hoy!

**Comment by yabellini** [comment]
Hecho!
